spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-interval: 30s
        instance-id: stock-service
        serviceName: s-${spring.application.name}
        management-port: 5555
      config:
        enabled: true
        format: YAML
        default-context: application
  application:
    name: stock-service
  config:
    import: optional:consul:localhost/8500
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.cloud.consul: DEBUG

kafka:
  bootstrapAddress: localhost:9092
