spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-interval: 30s
      config:
        enabled: true
        format: YAML
        default-context: application
  application:
    name: order-service
  config:
    import: optional:consul:localhost/8500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.cloud.consul: DEBUG

kafka:
  bootstrapAddress: localhost:9092
